In [1]:
import numpy as np
import pandas as pd

# Array creation

In [6]:
# creating array from python list with default data type
a = np.array([1,2,3])
print(type(a),a,a.dtype)

<class 'numpy.ndarray'> [1 2 3] int32


In [12]:
# array from python list with data type mentioned
b = np.array([1,2,3], dtype=np.int64)
print(type(b),b,b.dtype)

<class 'numpy.ndarray'> [1 2 3] int64


In [13]:
# ndarray from nested sequence
c = np.array([(1,2,3),(4,5,6)])
print(c,c.shape)

[[1 2 3]
 [4 5 6]] (2, 3)


In [17]:
# np.arange(start,stop,step), stop is not included and arange is best used for integer only
a = np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [18]:
b = np.arange(1,10,2)
print(b)

[1 3 5 7 9]


In [24]:
# np.linspace(start,stop,number of items,retstep=True[returns the interval if true]), best used for floats
c = np.linspace(1,5,10,retstep=True)
print(c)

(array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ]), 0.4444444444444444)


## 2D array creation

In [27]:
# np.eye(row, col, k=0[main diagonal if 0, upper diagonal if +ve and lower if -ve]) - to create identity matrix
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
b = np.eye(3,3,1) # upper diagonal is filled with ones
print(b)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [31]:
# np.diag(v,k=0) - returns a matrix with the elements on the kth diagonal
c = np.diag([1,2,3])
print(c)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [33]:
# If arg passed is a 2d array then it returns the kth[0 by default] diagonal only 
d = np.diag([(1,2,3),(4,5,6)])
d

array([1, 5])

## N dimensional arrays

In [34]:
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
b = np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Creating array from another array

In [38]:
a = np.array([1,2,3,4])
b = a[:2].copy()
print(a,b)

[1 2 3 4] [1 2]


In [39]:
c = np.copy(b)
print(c)

[1 2]
